### ISSUE TITLE
Occasional 'Object graph cannot be null' error

### ISSUE THREAD

**Issue by s6521d** [acarteas/FileCache#18]
Hi, I'm using File Cache as the persistence store for LazyCache and very occasionally when reading a cachce key I'm see an 'Object graph cannot be null' error and the file for the cache key on disk is 0 bytes in length.

You'll see from the code snippet in the attached that I've used lock(){} to try and rule out and threading issues.
[Object graph cannot be null - 2.pdf](https://github.com/acarteas/FileCache/files/2163822/Object.graph.cannot.be.null.-.2.pdf)

Any help much appreciated.

**Comment by acarteas** [comment]
Hmm.  That's weird.  Do you have any logs that give a better clue as to
under what circumstances this happens?  Regardless, I'll take a look at the
code and see if I can somehow control for / trap this error and maybe
return an empty string instead.

**Comment by acarteas** [comment]
I'm not sure.  Can you confirm that every call to Get is requesting a valid
cache key?

**Comment by s6521d** [comment]
Sorry for the delay, yes all calls are using a valid cache key. 
Is there anything around thread softy that  we need to be aware of when using FileCache?

**Comment by s6521d** [comment]
I've just written a console application that uses two threads to read the same key from a static instance LazyCache backed by file cache and I very quickly see the Object graph cannot be null' error.

**Comment by acarteas** [comment]
That'd be great.  Also, try the latest version of the source on Github (not posted to nuget yet).  It includes a PR that fixes a bug related to file accessing.

**Comment by s6521d** [comment]
Hi, 
Sorry for the delay in replying to you. I'm having issues building the current source, is there any chance you zip it up built so I can add the dll file to my test solution?
Kind regards,
Steve Dawkins 

    On Monday, 17 September 2018, 19:00, Adam Carter <notifications@github.com> wrote:
 

 That'd be great. Also, try the latest version of the source on Github (not posted to nuget yet). It includes a PR that fixes a bug related to file accessing.—

**Comment by acarteas** [comment]
I just pushed version 2.1.3 to NuGet, which contains the fix that appears to address the problem that you were having in your example project.  Take a look and let me know what you think.

**Comment by s6521d** [comment]
Hi, I've updated to 2.1.3 and its a lot better but with the sleep removed from the test program I'm still seeing the occasional  Object  graph error, below is an extract from the log so far, I'll keep this running for 24hrs to see how many more times we see errors:

29/09/2018 13:01:50 Reads: 70100 Errors: 0 Thread[33]
29/09/2018 13:01:51 Reads: 70200 Errors: 0 Thread[36]
EXCEPTION Read: 70252 29/09/2018 13:01:51 Thread[34] Object Graph cannot be null.
Parameter name: graph
EXCEPTION Read: 70264 29/09/2018 13:01:51 Thread[28] Object Graph cannot be null.
Parameter name: graph
29/09/2018 13:01:51 Reads: 70300 Errors: 2 Thread[21]
EXCEPTION Read: 70305 29/09/2018 13:01:51 Thread[32] Object Graph cannot be null.
Parameter name: graph
29/09/2018 13:01:52 Reads: 70400 Errors: 3 Thread[24]
29/09/2018 13:01:52 Reads: 70500 Errors: 3 Thread[25]

**Comment by acarteas** [comment]
Okay,

I'll remove the sleep (line 57?) and see what I get.

--Adam

**Comment by s6521d** [comment]
Hi, I ran the test several times yesterday and have observed that the errors are either sparse to reproduce or  prolific in bursts. In the attached word document you'll see both the _object graph_ and _access to path errors_ at read's 1,057,179 and 1,057,207 followed by 4,336,463 reads without any error. This  suggests to me a very small window and timing scenario that's difficult to hit but occasionally is by this stress test. But one that could be hit by just two threads in an IIS web application under the correct circumstances.  I've also added the source code for the program  used to produce these results. 
[FileCacheLog-300918.docx](https://github.com/acarteas/FileCache/files/2432909/FileCacheLog-300918.docx)
[DfE-403 (2).zip](https://github.com/acarteas/FileCache/files/2432917/DfE-403.2.zip)

**Comment by acarteas** [comment]
This is going to be very difficult to debug.  I did find another call to File.SetLastAccessTime that I don't think was needed.  I've removed that call as well.  However, it's hard to tell if that actually fixed anything.  I'll let it  run all day on my work machine tomorrow.

**Comment by acarteas** [comment]
I left the program running all weekend on my work PC and didn't get any errors.  Try the latest develop checkin or the attached ZIP of the compiled binary and let me know how it works out on your end.
[FC.zip](https://github.com/acarteas/FileCache/files/2456998/FC.zip)

**Comment by s6521d** [comment]
Hi, I've tested and it seems to be solid now, can you publish a new version to NUGET? Many thanks for your support.

**Comment by acarteas** [comment]
I just pushed a new version (2.1.4) to nuget.  I would expect it to be made available within the next 30 minutes or so.  If I don't hear back within a few days, I'll close this thread as completed.
